# coding: utf-8

"""
    Foxhole WarAPI

    The War API allows developers to query information about the state of the current Foxhole World Conquest.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from warapi.models.map import Map

class TestMap(unittest.TestCase):
    """Map unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Map:
        """Test Map
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Map`
        """
        model = Map()
        if include_optional:
            return Map(
                region_id = 43,
                scorched_victory_towns = 0,
                map_items = [
                    warapi.models.map_item.MapItem(
                        team_id = 'NONE', 
                        icon_type = 61, 
                        x = 0.74243516, 
                        y = 0.7063276, 
                        flags = 0, 
                        view_direction = 0, )
                    ],
                map_items_c = [
                    warapi.models.map_item.MapItem(
                        team_id = 'NONE', 
                        icon_type = 61, 
                        x = 0.74243516, 
                        y = 0.7063276, 
                        flags = 0, 
                        view_direction = 0, )
                    ],
                map_items_w = [
                    warapi.models.map_item.MapItem(
                        team_id = 'NONE', 
                        icon_type = 61, 
                        x = 0.74243516, 
                        y = 0.7063276, 
                        flags = 0, 
                        view_direction = 0, )
                    ],
                map_text_items = [
                    warapi.models.map_text_items.MapTextItems(
                        text = 'Abandoned Ward', 
                        x = 0.74243516, 
                        y = 0.7063276, 
                        map_marker_type = 'Major', )
                    ],
                last_updated = 1703866455284,
                version = 2
            )
        else:
            return Map(
        )
        """

    def testMap(self):
        """Test Map"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
