# coding: utf-8

"""
    WarAPI

    The War API allows developers to query information about the state of the current Foxhole World Conquest.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import warapi_client
from warapi_client.models.faction_enum import FactionEnum  # noqa: E501
from warapi_client.rest import ApiException


class TestFactionEnum(unittest.TestCase):
    """FactionEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFactionEnum(self):
        """Test FactionEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = warapi_client.models.faction_enum.FactionEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
