# coding: utf-8

"""
    WarAPI

    The War API allows developers to query information about the state of the current Foxhole World Conquest.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import warapi_client
from warapi_client.api.maps_api import MapsApi  # noqa: E501
from warapi_client.rest import ApiException


class TestMapsApi(unittest.TestCase):
    """MapsApi unit test stubs"""

    def setUp(self):
        self.api = MapsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_map_dynamic(self):
        """Test case for get_map_dynamic

        Dynamic map data includes map icons that could change over the lifecycle of a map. This includes static bases and static base build sites.  # noqa: E501
        """
        pass

    def test_get_map_static(self):
        """Test case for get_map_static

        Static map data includes things that never change over the lifecycle of a map. This includes map text labels, resource nodes, and world structures.  # noqa: E501
        """
        pass

    def test_get_maps(self):
        """Test case for get_maps

        Returns a list of the active World Conquest map names.  # noqa: E501
        """
        pass

    def test_get_war_report(self):
        """Test case for get_war_report

        Returns the number of enlistments, casualties, and other map specific information.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
