# coding: utf-8

"""
    WarAPI

    The War API allows developers to query information about the state of the current Foxhole World Conquest.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import warapi_client
from warapi_client.models.map import Map  # noqa: E501
from warapi_client.rest import ApiException


class TestMap(unittest.TestCase):
    """Map unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMap(self):
        """Test Map"""
        # FIXME: construct object with mandatory attributes with example values
        # model = warapi_client.models.map.Map()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
