# coding: utf-8

"""
    WarAPI

    The War API allows developers to query information about the state of the current Foxhole World Conquest.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from warapi_client.models.war import War

class TestWar(unittest.TestCase):
    """War unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> War:
        """Test War
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `War`
        """
        model = War()
        if include_optional:
            return War(
                war_id = '4ef9c639-c660-4a57-ac96-8521c7e4b20e',
                war_number = 109,
                winner = 'NONE',
                conquest_start_time = 1701801322204,
                conquest_end_time = 56,
                resistance_start_time = 56,
                required_victory_towns = 32
            )
        else:
            return War(
        )
        """

    def testWar(self):
        """Test War"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
