# coding: utf-8

"""
    WarAPI

    The War API allows developers to query information about the state of the current Foxhole World Conquest.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import warapi_client
from warapi_client.models.war_report import WarReport  # noqa: E501
from warapi_client.rest import ApiException


class TestWarReport(unittest.TestCase):
    """WarReport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWarReport(self):
        """Test WarReport"""
        # FIXME: construct object with mandatory attributes with example values
        # model = warapi_client.models.war_report.WarReport()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
