# coding: utf-8

"""
    Foxhole WarAPI

    The War API allows developers to query information about the state of the current Foxhole World Conquest.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from warapi.models.map_item import MapItem

class TestMapItem(unittest.TestCase):
    """MapItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MapItem:
        """Test MapItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MapItem`
        """
        model = MapItem()
        if include_optional:
            return MapItem(
                team_id = 'NONE',
                icon_type = 61,
                x = 0.74243516,
                y = 0.7063276,
                flags = 0,
                view_direction = 0
            )
        else:
            return MapItem(
        )
        """

    def testMapItem(self):
        """Test MapItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
