# coding: utf-8

"""
    Foxhole WarAPI

    The War API allows developers to query information about the state of the current Foxhole World Conquest.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from warapi.api.maps_api import MapsApi


class TestMapsApi(unittest.TestCase):
    """MapsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MapsApi()

    def tearDown(self) -> None:
        pass

    def test_get_map_dynamic(self) -> None:
        """Test case for get_map_dynamic

        Dynamic map data includes map icons that could change over the lifecycle of a map. This includes static bases and static base build sites.
        """
        pass

    def test_get_map_static(self) -> None:
        """Test case for get_map_static

        Static map data includes things that never change over the lifecycle of a map. This includes map text labels, resource nodes, and world structures.
        """
        pass

    def test_get_maps(self) -> None:
        """Test case for get_maps

        Returns a list of the active World Conquest map names.
        """
        pass

    def test_get_war_report(self) -> None:
        """Test case for get_war_report

        Returns the number of enlistments, casualties, and other map specific information.
        """
        pass


if __name__ == '__main__':
    unittest.main()
