# coding: utf-8

"""
    WarAPI

    The War API allows developers to query information about the state of the current Foxhole World Conquest.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from warapi_client.models.faction_enum import FactionEnum

class TestFactionEnum(unittest.TestCase):
    """FactionEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFactionEnum(self):
        """Test FactionEnum"""
        # inst = FactionEnum()

if __name__ == '__main__':
    unittest.main()
