# coding: utf-8

"""
    Foxhole WarAPI

    The War API allows developers to query information about the state of the current Foxhole World Conquest.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from warapi.models.war_report import WarReport

class TestWarReport(unittest.TestCase):
    """WarReport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WarReport:
        """Test WarReport
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WarReport`
        """
        model = WarReport()
        if include_optional:
            return WarReport(
                total_enlistments = 148,
                colonial_casualties = 202,
                warden_casualties = 222,
                day_of_war = 2
            )
        else:
            return WarReport(
        )
        """

    def testWarReport(self):
        """Test WarReport"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
