# coding: utf-8

"""
    WarAPI

    The War API allows developers to query information about the state of the current Foxhole World Conquest.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from warapi_client.api.external_api import ExternalApi


class TestExternalApi(unittest.TestCase):
    """ExternalApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExternalApi()

    def tearDown(self) -> None:
        pass

    def test_get_shard_status(self) -> None:
        """Test case for get_shard_status

        Hidden endpoint returning information about each server.
        """
        pass


if __name__ == '__main__':
    unittest.main()
