# coding: utf-8

"""
    WarAPI

    The War API allows developers to query information about the state of the current Foxhole World Conquest.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import warapi_client
from warapi_client.api.external_api import ExternalApi  # noqa: E501
from warapi_client.rest import ApiException


class TestExternalApi(unittest.TestCase):
    """ExternalApi unit test stubs"""

    def setUp(self):
        self.api = ExternalApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_shard_status(self):
        """Test case for get_shard_status

        Hidden endpoint returning information about each server.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
