# coding: utf-8

# flake8: noqa

"""
    Foxhole WarAPI

    The War API allows developers to query information about the state of the current Foxhole World Conquest.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from warapi.api.external_api import ExternalApi
from warapi.api.maps_api import MapsApi
from warapi.api.war_api import WarApi

# import ApiClient
from warapi.api_response import ApiResponse
from warapi.api_client import ApiClient
from warapi.configuration import Configuration
from warapi.exceptions import OpenApiException
from warapi.exceptions import ApiTypeError
from warapi.exceptions import ApiValueError
from warapi.exceptions import ApiKeyError
from warapi.exceptions import ApiAttributeError
from warapi.exceptions import ApiException

# import models into sdk package
from warapi.models.faction_enum import FactionEnum
from warapi.models.map import Map
from warapi.models.map_item import MapItem
from warapi.models.map_text_items import MapTextItems
from warapi.models.server_connection_info import ServerConnectionInfo
from warapi.models.shard_status import ShardStatus
from warapi.models.war import War
from warapi.models.war_report import WarReport
