# coding: utf-8

"""
    WarAPI

    The War API allows developers to query information about the state of the current Foxhole World Conquest.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "foxhole-warapi-client"
VERSION = "1.0.1"
PYTHON_REQUIRES = ">=3.7"
REQUIRES = [
    "urllib3 >= 1.25.3, < 2.1.0",
    "python-dateutil",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="WarAPI",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="https://github.com/Opa-/foxhole-warapi-python-client",
    keywords=["OpenAPI", "OpenAPI-Generator", "WarAPI"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    The War API allows developers to query information about the state of the current Foxhole World Conquest.
    """,  # noqa: E501
    package_data={"warapi_client": ["py.typed"]},
)
