# coding: utf-8

# flake8: noqa
"""
    WarAPI

    The War API allows developers to query information about the state of the current Foxhole World Conquest.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from warapi_client.models.faction_enum import FactionEnum
from warapi_client.models.map import Map
from warapi_client.models.map_item import MapItem
from warapi_client.models.map_text_items import MapTextItems
from warapi_client.models.server_connection_info import ServerConnectionInfo
from warapi_client.models.shard_status import ShardStatus
from warapi_client.models.war import War
from warapi_client.models.war_report import WarReport
