# coding: utf-8

"""
    Foxhole WarAPI

    The War API allows developers to query information about the state of the current Foxhole World Conquest.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FactionEnum(str, Enum):
    """
    FactionEnum
    """

    """
    allowed enum values
    """
    NONE = 'NONE'
    WARDENS = 'WARDENS'
    COLONIALS = 'COLONIALS'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FactionEnum from a JSON string"""
        return cls(json.loads(json_str))


