# coding: utf-8

# flake8: noqa

"""
    WarAPI

    The War API allows developers to query information about the state of the current Foxhole World Conquest.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.1"

# import apis into sdk package
from warapi_client.api.external_api import ExternalApi
from warapi_client.api.maps_api import MapsApi
from warapi_client.api.war_api import WarApi

# import ApiClient
from warapi_client.api_response import ApiResponse
from warapi_client.api_client import ApiClient
from warapi_client.configuration import Configuration
from warapi_client.exceptions import OpenApiException
from warapi_client.exceptions import ApiTypeError
from warapi_client.exceptions import ApiValueError
from warapi_client.exceptions import ApiKeyError
from warapi_client.exceptions import ApiAttributeError
from warapi_client.exceptions import ApiException

# import models into sdk package
from warapi_client.models.faction_enum import FactionEnum
from warapi_client.models.map import Map
from warapi_client.models.map_item import MapItem
from warapi_client.models.map_text_items import MapTextItems
from warapi_client.models.server_connection_info import ServerConnectionInfo
from warapi_client.models.shard_status import ShardStatus
from warapi_client.models.war import War
from warapi_client.models.war_report import WarReport
